### ISSUE TITLE
Android M  execStartActivity  Exception

### ISSUE THREAD

**Issue by bunnyblue** [bunnyblue/OpenAtlas#173]
```

07-31 15:21:40.014  10581-10581/com.openatlas.launcher W/System.err﹕ com.openatlas.hack.Hack$HackDeclaration$HackAssertionException: java.lang.NoSuchMethodException: execStartActivity [class android.content.Context, interface android.os.IBinder, interface android.os.IBinder, class android.app.Fragment, class android.content.Intent, int, class android.os.Bundle]
07-31 15:21:40.014  10581-10581/com.openatlas.launcher W/System.err﹕ at com.openatlas.hack.Hack$HackedMethod.<init>(Hack.java:279)
07-31 15:21:40.014  10581-10581/com.openatlas.launcher W/System.err﹕ at com.openatlas.hack.Hack$HackedClass.method(Hack.java:108)
07-31 15:21:40.014  10581-10581/com.openatlas.launcher W/System.err﹕ at com.openatlas.runtime.InstrumentationHook.<init>(InstrumentationHook.java:290)
07-31 15:21:40.014  10581-10581/com.openatlas.launcher W/System.err﹕ at com.openatlas.framework.Atlas.init(Atlas.java:97)
07-31 15:21:40.015  10581-10581/com.openatlas.launcher W/System.err﹕ at com.openatlas.android.initializer.OpenAtlasInitializer.init(OpenAtlasInitializer.java:95)
07-31 15:21:40.015  10581-10581/com.openatlas.launcher W/System.err﹕ at com.openatlas.android.lifecycle.AtlasApp.attachBaseContext(AtlasApp.java:220)
07-31 15:21:40.015  10581-10581/com.openatlas.launcher W/System.err﹕ at android.app.Application.attach(Application.java:187)
07-31 15:21:40.015  10581-10581/com.openatlas.launcher W/System.err﹕ at android.app.Instrumentation.newApplication(Instrumentation.java:997)
07-31 15:21:40.015  10581-10581/com.openatlas.launcher W/System.err﹕ at android.app.Instrumentation.newApplication(Instrumentation.java:981)
07-31 15:21:40.015  10581-10581/com.openatlas.launcher W/System.err﹕ at android.app.LoadedApk.makeApplication(LoadedApk.java:573)
07-31 15:21:40.015  10581-10581/com.openatlas.launcher W/System.err﹕ at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4678)
07-31 15:21:40.015  10581-10581/com.openatlas.launcher W/System.err﹕ at android.app.ActivityThread.-wrap1(ActivityThread.java)
07-31 15:21:40.015  10581-10581/com.openatlas.launcher W/System.err﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1406)
07-31 15:21:40.015  10581-10581/com.openatlas.launcher W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
07-31 15:21:40.015  10581-10581/com.openatlas.launcher W/System.err﹕ at android.os.Looper.loop(Looper.java:148)
07-31 15:21:40.015  10581-10581/com.openatlas.launcher W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5415)
07-31 15:21:40.016  10581-10581/com.openatlas.launcher W/System.err﹕ at java.lang.reflect.Method.invoke(Native Method)
07-31 15:21:40.016  10581-10581/com.openatlas.launcher W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
07-31 15:21:40.016  10581-10581/com.openatlas.launcher W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
07-31 15:21:40.016  10581-10581/com.openatlas.launcher W/System.err﹕ Caused by: java.lang.NoSuchMethodException: execStartActivity [class android.content.Context, interface android.os.IBinder, interface android.os.IBinder, class android.app.Fragment, class android.content.Intent, int, class android.os.Bundle]
07-31 15:21:40.016  10581-10581/com.openatlas.launcher W/System.err﹕ at java.lang.Class.getMethod(Class.java:624)
07-31 15:21:40.016  10581-10581/com.openatlas.launcher W/System.err﹕ at java.lang.Class.getDeclaredMethod(Class.java:586)
07-31 15:21:40.017  10581-10581/com.openatlas.launcher W/System.err﹕ at com.openatlas.hack.Hack$HackedMethod.<init>(Hack.java:272)
07-31 15:21:40.017  10581-10581/com.openatlas.launcher W/System.err﹕ ... 18 more
```

**Comment by bunnyblue** [comment]
function not available
