### ISSUE TITLE
Activity继承AppCompatActivity的问题

### ISSUE THREAD

**Issue by lizhangqu** [bunnyblue/OpenAtlas#178]
继承AppCompatActivity程序可独立运行，集成为插件后，便会报错。栈跟踪如下

```
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
08-12 10:51:10.715  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.support.v7.app.AppCompatDelegateImplBase.onCreate(AppCompatDelegateImplBase.java:124)
08-12 10:51:10.717  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.support.v7.app.AppCompatDelegateImplV7.onCreate(AppCompatDelegateImplV7.java:146)
08-12 10:51:10.717  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:59)
08-12 10:51:10.719  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at com.lizhangqu.test.MainActivity.onCreate(MainActivity.java:10)
08-12 10:51:10.719  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.app.Activity.performCreate(Activity.java:5251)
08-12 10:51:10.720  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
08-12 10:51:10.721  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at com.openatlas.runtime.InstrumentationHook.callActivityOnCreate(InstrumentationHook.java:536)
08-12 10:51:10.722  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2153)
08-12 10:51:10.722  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238)
08-12 10:51:10.722  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.app.ActivityThread.access$800(ActivityThread.java:138)
08-12 10:51:10.724  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201)
08-12 10:51:10.724  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at com.openatlas.hack.AndroidHack$HandlerHack.handleMessage(AndroidHack.java:62)
08-12 10:51:10.724  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:98)
08-12 10:51:10.725  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.os.Looper.loop(Looper.java:136)
08-12 10:51:10.726  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5016)
08-12 10:51:10.727  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
08-12 10:51:10.727  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
08-12 10:51:10.727  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
08-12 10:51:10.728  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
08-12 10:51:10.729  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
08-12 10:51:10.734  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.edu.zafu.atlasdemo/com.lizhangqu.test.MainActivity}: java.lang.RuntimeException: (1)Paths in ContextThemeWrapper_mResources:[/system/framework/framework-res.apk, /system/app/miui.apk, /system/app/miuisystem.apk, /system/framework/framework-ext-res.apk, /data/app/cn.edu.zafu.atlasdemo-2.apk, /data/data/cn.edu.zafu.atlasdemo/lib/libcom_lizhangqu_test.so] paths in runtime:newDelegateResources [/data/app/cn.edu.zafu.atlasdemo-2.apk,/data/data/cn.edu.zafu.atlasdemo/lib/libcom_lizhangqu_test.so,]
08-12 10:51:10.736  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2189)
08-12 10:51:10.737  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2238)
08-12 10:51:10.737  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.app.ActivityThread.access$800(ActivityThread.java:138)
08-12 10:51:10.737  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201)
08-12 10:51:10.737  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at com.openatlas.hack.AndroidHack$HandlerHack.handleMessage(AndroidHack.java:62)
08-12 10:51:10.737  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:98)
08-12 10:51:10.739  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.os.Looper.loop(Looper.java:136)
08-12 10:51:10.739  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5016)
08-12 10:51:10.740  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
08-12 10:51:10.741  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
08-12 10:51:10.741  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
08-12 10:51:10.742  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
08-12 10:51:10.742  16878-16878/cn.edu.zafu.atlasdemo W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
```

然而确实已经设置了该主题，依然无效
```
  <activity
            android:name="com.lizhangqu.test.MainActivity"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"
            >
        </activity>
```

**Comment by bunnyblue** [comment]
你的主题在宿主的manifest设置了？

**Comment by lizhangqu** [comment]
宿主和插件里都设置了

**Comment by bunnyblue** [comment]
你看下 https://github.com/bunnyblue/OpenAtlas/issues/137 这个跟你的类似应该

**Comment by lizhangqu** [comment]
还是不行啊。。。这样太蛋疼了，移植的话还不能用v7兼容包里的AppCompatActivity，正常程序可以跑，一转插件就不行，由于我用到了主题资源Theme.AppCompat.Light.NoActionBar，aar没办法用provided形式，只能宿主和插件都把v7兼容包编译进去了，宿主和插件的清单文件都做了主题声明，怎么修改都报java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

**Comment by bunnyblue** [comment]
不行啊，你看137，编译插件的时jar只能引用进去，这个之前测试了没问题，你不能把jar编译的插件里面去，主题可以只在宿主里面注册

**Comment by lizhangqu** [comment]
但是需要引用v7包里的资源，如果只引用jar是没问题的啊，加上资源就直接引用aar了，aar不能以provided形式编译

**Comment by bunnyblue** [comment]
这个问题我知道，你在插件的清单文件把v7的资源移除掉就行，这个没关系，等后面支持共享资源
编译的时候v7只能做引用，不参与编译

**Comment by lizhangqu** [comment]
解决了，解决方法和你说的差不多，把插件所有和v7资源相关的主题移除，在宿主中指定主题，并在插件中以provided形式提供v7的jar，但是这样依然有一个问题就是菜单文件需要使用命名空间app:showAsAction="always"，这个在V7资源包里，并且插件里需要使用，目前的方法就是把这句移除，但是移除后菜单显示位置就有所不同了(用的Toolbar)，即使把命名空间改成android，原来的在toolbar上显示的子菜单也会自动移到overflow menu中显示。有没有什么好的解决方法

**Comment by bunnyblue** [comment]
这个可以在代码里设置我记得是，你参考下http://stackoverflow.com/questions/15138305/set-androidshowasaction-ifroomwithtext-programmatically，应该是都可以设置的，在代码设置

**Comment by lizhangqu** [comment]
期待下一个版本，这个issue就先closed掉吧

**Comment by bunnyblue** [comment]
👌
